offload/wlan/lmac_offload_if/ol_ath_ucfg.c
offload/wlan/lmac_offload_if/ol_if_ath.c
offload/wlan/lmac_offload_if/ol_if_rates.c
offload/wlan/lmac_offload_if/ol_if_vap.c
offload/wlan/lmac_offload_if/ol_if_node.c
offload/wlan/lmac_offload_if/ol_if_cwm.c
offload/wlan/lmac_offload_if/ol_if_dfs.c
offload/wlan/lmac_offload_if/ol_if_phyerr.c
offload/wlan/lmac_offload_if/ol_helper.c
offload/wlan/lmac_offload_if/ol_if_ath_config.c
offload/wlan/lmac_offload_if/ol_if_eeprom.c
offload/wlan/lmac_offload_if/ol_if_thermal.c
offload/wlan/umac_offload_if/ol_if_beacon.c
offload/wlan/umac_offload_if/ol_if_mgmt.c
offload/wlan/umac_offload_if/ol_if_power.c
offload/wlan/umac_offload_if/ol_if_nl.c
offload/wlan/umac_offload_if/ol_if_rtt.c
offload/wlan/umac_offload_if/ol_if_lowi.c
offload/wlan/umac_offload_if/ol_if_resmgr.c
offload/ol_cfg/ol_cfg.c
offload/os/linux/ol_ath_linux.c
offload/os/linux/ol_ath_iw_handler.c
offload/os/linux/netbuf.c
cmn_dev/hif/src/regtable.c
offload/wlan/lmac_offload_if/ol_if_me.c
cmn_dev/target_if/scan/src/target_if_scan.c
cmn_dev/target_if/ftm/src/target_if_ftm.c
cmn_dev/target_if/dp/src/target_if_dp.c
cmn_dev/target_if/son/src/target_if_son.c
pld/src/pld_common.c
pld/src/pld_pcie.c
pld/src/pld_ahb.c
cmn_dev/target_if/init_deinit/src/init_event_handler.c
cmn_dev/target_if/init_deinit/src/service_ready_util.c
cmn_dev/target_if/init_deinit/src/init_cmd_api.c
cmn_dev/target_if/init_deinit/src/init_deinit_lmac.c
offload/wlan/target_if/init_deinit/src/init_deinit_ops.c
offload/wlan/lmac_offload_if/wlan_lmac_dispatcher.c
cmn_dev/dp/cmn_dp_api/dp_ratetable.c
component_dev/dp/src/dp_rate_stats.c
cmn_dev/dp/cmn_dp_api/dp_cal_client_api.c
cmn_dev/target_if/mlme/vdev_mgr/src/target_if_vdev_mgr_rx_ops.c
cmn_dev/target_if/mlme/vdev_mgr/src/target_if_vdev_mgr_tx_ops.c
offload/wlan/lmac_offload_if/ol_if_stats.c
cmn_dev/target_if/cp_stats/src/target_if_cp_stats.c
cmn_dev/target_if/green_ap/src/target_if_green_ap.c
cmn_dev/target_if/dfs/src/target_if_dfs.c
cmn_dev/target_if/dfs/src/target_if_dfs_full_offload.c
cmn_dev/target_if/dfs/src/target_if_dfs_partial_offload.c
offload/wlan/target_if/atf/target_if_atf.c
offload/wlan/target_if/sa_api/target_if_sa_api.c
component_dev/target_if/cfr/src/target_if_cfr.c
component_dev/target_if/cfr/src/target_if_cfr_8074v2.c
component_dev/target_if/cfr/src/target_if_cfr_wifi2_0.c
cmn_dev/target_if/wifi_pos/src/target_if_wifi_pos.c
offload/wlan/target_if/offchan_txrx/target_if_offchan_txrx_api.c
offload/wlan/target_if/fils_discovery/target_if_fd.c
offload/wlan/txrx/ol_if_mat.c
qca_ol/osif_ol.c
qca_ol/qca_ol_if.c
qca_ol/qca_ol_module.c
cmn_dev/wmi/src/wmi_unified.c
cmn_dev/wmi/src/wmi_unified_api.c
cmn_dev/wmi/src/wmi_unified_reg_api.c
cmn_dev/wmi/src/wmi_unified_dfs_api.c
component_dev/wmi/src/wmi_unified_smart_ant_api.c
component_dev/wmi/src/wmi_unified_atf_api.c
component_dev/wmi/src/wmi_unified_ap_api.c
cmn_dev/wmi/src/wmi_unified_dbr_api.c
cmn_dev/wmi/src/wmi_unified_twt_api.c
offload/wlan/regdmn/ol_regdomain.c
offload/os/linux/ol_ioctl_acfg.c
cmn_dev/htc/htc_send.c
cmn_dev/htc/htc_recv.c
cmn_dev/htc/htc_services.c
cmn_dev/htc/htc.c
cmn_dev/hif/src/ce/ce_service.c
cmn_dev/hif/src/ce/ce_main.c
cmn_dev/hif/src/ce/ce_diag.c
cmn_dev/hif/src/ce/ce_tasklet.c
cmn_dev/hif/src/pcie/if_pci.c
offload/os/linux/ath_pci.c
offload/os/linux/ath_sysfs.c
cmn_dev/hif/src/hif_exec.c
cmn_dev/hif/src/hif_main.c
cmn_dev/hif/src/mp_dev.c
cmn_dev/hif/src/dispatcher/multibus.c
cmn_dev/hif/src/dispatcher/multibus_pci.c
cmn_dev/hif/src/dispatcher/dummy.c
cmn_dev/hif/src/ath_procfs.c
offload/os/linux/ath_ahb.c
offload/os/linux/ath_pld.c
cmn_dev/hif/src/snoc/if_ahb.c
cmn_dev/hif/src/snoc/if_ahb_reset.c
cmn_dev/hif/src/dispatcher/multibus_ahb.c
cmn_dev/hif/src/hif_napi.c
os/linux/src/osif_rawmode.c
os/linux/src/osif_rawmode_sim.c
offload/wlan/ath_pktlog/linux_ac.c
offload/wlan/ath_pktlog/pktlog_ac.c
offload/wlan/ath_pktlog/pktlog_internal.c
offload/wlan/ath_pktlog/linux_remote_pktlog.c
cmn_dev/target_if/core/src/target_if_main.c
cmn_dev/target_if/regulatory/src/target_if_reg.c
cmn_dev/utils/fwlog/fw_dbglog_api.c
cmn_dev/hif/src/ar6004def.c
cmn_dev/hif/src/ar9888def.c
cmn_dev/hif/src/ar6320def.c
cmn_dev/hif/src/ar900Bdef.c
cmn_dev/hif/src/qca9984def.c
cmn_dev/hif/src/qca9888def.c
offload/wlan/txrx/ol_ratetable.c
offload/wlan/lmac_offload_if/ol_if_smart_ant.c
offload/wlan/lmac_offload_if/ol_if_stats_wifi2.c
offload/wlan/lmac_offload_if/wifi2.0/ol_if_ath_2_0.c
cmn_dev/hif/src/ipq4019def.c
offload/wlan/lmac_offload_if/ol_if_stats_wifi3.c
cmn_dev/target_if/direct_buf_rx/src/target_if_direct_buf_rx_api.c
cmn_dev/target_if/direct_buf_rx/src/target_if_direct_buf_rx_main.c
cmn_dev/hif/src/qca8074def.c
cmn_dev/hif/src/qca8074v2def.c
cmn_dev/hal/wifi3.0/hal_srng.c
cmn_dev/hal/wifi3.0/hal_reo.c
cmn_dev/hal/wifi3.0/qca8074v1/hal_8074v1.c
cmn_dev/hal/wifi3.0/qca8074v2/hal_8074v2.c
qca_ol/if_ath_pci.c
qca_ol/if_ath_ahb.c