offload/bmi/bmi.c
offload/wlan/lmac_offload_if/ol_if_bmi.c
cmn_dev/hif/src/ce/ce_bmi.c
cmn_dev/hif/src/ce/ce_service_legacy.c
cmn_dev/hif/src/hif_main_legacy.c
offload/wds/wds_addr.c
offload/misc/dbglog_host.c
component_dev/wmi/src/wmi_unified_non_tlv.c
offload/wlan/ath_pktlog/wifi2.0/pktlog_internal_2_0.c
offload/wlan/txrx/ol_rx.c
offload/wlan/txrx/ol_rx_fwd.c
offload/wlan/txrx/ol_rx_defrag.c
offload/wlan/txrx/ol_txrx_peer_find.c
offload/wlan/txrx/ol_rx_pn.c
offload/wlan/txrx/ol_rx_reorder.c
offload/wlan/txrx/ol_tx.c
offload/wlan/txrx/ol_tx_desc.c
offload/wlan/txrx/ol_txrx.c
offload/wlan/txrx/ol_txrx_cfg.c
offload/wlan/txrx/ol_tx_send.c
offload/wlan/txrx/ol_txrx_prot_an.c
offload/wlan/txrx/ol_txrx_event.c
offload/wlan/txrx/ol_tx_me.c
offload/wlan/txrx/ol_rawmode_rx.c
offload/wlan/txrx/ol_rawmode_tx.c
offload/wlan/txrx/ol_tx_tso_sg.c
offload/wlan/txrx/ol_tx_sg.c
offload/htt/htt.c
offload/htt/htt_h2t.c
offload/htt/htt_rx.c
offload/htt/htt_t2h.c
offload/htt/htt_fw_stats.c
offload/htt/htt_tx.c
offload/hw/ar.c
offload/hw/QCA9984/rx_desc.c
offload/hw/AR900B/rx_desc.c
offload/hw/AR9888/rx_desc.c
qca_ol/wifi2.0/qca_ol_if_wifi2_0.c
qca_ol/wifi2.0/if_ath_pci.c
qca_ol/wifi2.0/if_ath_ahb.c
